server:
  error:
    include-message: always
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/cashReceipt}
    username: ${POSTGRES_USER:cashReceiptUser}
    password: ${POSTGRES_PASSWORD:cashReceiptPassword}
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/cashReceipt}
    user: ${DB_MIGRATION_USER:cashReceiptUser}
    password: ${DB_MIGRATION_PASSWORD:cashReceiptPassword}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob.non_contextual_creation: true
        connection.autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner_mode: "OFF"

promotional:
  min-quantity-to-apply-discount: 6
  discount-percentage: 10

export:
  destination-folder-path: D:\temp\receipt-export
